import {
  Calculator,
  ClipboardList,
  Contact,
  HandCoins,
  Home,
  IndianRupee,
  LayoutPanelLeft,
  Medal,
  MessageSquareMore,
  StickyNote,
  User,
  User2,
  Users,
  UsersRound,
} from "lucide-react";
import { FaUserEdit, FaUserGraduate, FaUsers } from "react-icons/fa";
import {
  PiRanking,
  PiRankingDuotone,
  PiRankingFill,
  PiRankingLight,
} from "react-icons/pi";

export const MENU = [
  {
    lable: "HOME",
    path: "/",
    icon: () => <Home className="h-4 w-4" />,
    Permission: "",
  },
  {
    lable: "GENERAL REGISTER",
    path: "/student",
    icon: () => <ClipboardList className="h-4 w-4" />,
    Permission: "General Register",
  },
  {
    lable: "CHATS",
    path: "/chats",
    icon: () => <MessageSquareMore className="h-4 w-4" />,
    Permission: "",
  },
  {
    lable: "STANDARD",
    path: "/standard",
    icon: () => <Users className="h-4 w-4" />,
    Permission: "Standard And Caste Report",
  },
  {
    lable: "CASTE REPORT",
    path: "/caste-report",
    icon: () => <Contact className="h-4 w-4" />,
    Permission: "Standard And Caste Report",
  },
  // {
  //   lable: "STUDENT",
  //   path: "/update",
  //   icon: () => <UsersRound className="h-4 w-4" />,
  //   Permission: "Student Update and History",
  // },
  {
    lable: "FEES",
    // path: "/fee-type",
    icon: () => <HandCoins className="h-4 w-4" />,
    Permission: "Payment Fees",
    submenu: [
      {
        lable: "FEE STRUCTURE",
        path: "/fee-type",
        icon: () => <LayoutPanelLeft className="h-4 w-4" />,
        permission: "Payment Fees",
      },
      {
        lable: "PAYMENT",
        path: "/payment",
        icon: () => <IndianRupee className="h-4 w-4" />,
        permission: "Payment Fees",
      },
    ],
  },
  // {
  //   lable: "PAYMENT",
  //   path: "/payment",
  //   icon: () => <IndianRupee className="h-4 w-4" />,
  //   Permission: "Payment",
  // },
  {
    lable: "REPORT",
    path: "/report",
    icon: () => <StickyNote className="h-4 w-4" />,
    Permission: "Fee Report",
  },
  {
    lable: "RESULT",
    // path: "/exam-template",
    icon: () => <FaUserGraduate className="h-4 w-4" />,
    Permission: "Exam",
    submenu: [
      {
        lable: "TEST",
        path: "/exam-template",
        icon: () => <Medal className="h-4 w-4" />,
        permission: "Exam",
      },
      {
        lable: "EXAM",
        path: "/exam-result",
        icon: () => <PiRanking className="h-4 w-4" />,
        permission: "Exam",
      },
    ],
  },
];

export const studentDetail = {
  // grno: 1,
  first_name: "",
  last_name: "",
  middle_name: "",
  mother_name: "",
  birth_date: "",
  birth_place: "",
  religion: "હિન્દુ",
  category: "જનરલ",
  caste: "",
  admission_std: "13",
  admission_date: "2024",
  standard: "13",
  section: "A",
  last_school: "",
  city: "",
  district: "",
  address: "",
  mobile_no: "",
  status: "ચાલુ",
  gender: "કુમાર",
  udise_no: "",
  aadhar_no: "",
  academic_year: "2024-25",
  account_no: "",
  name_on_passbook: "",
  bank_name: "",
  ifsc_code: "",
  left_school_std: "",
  reason: "",
  progress: "1",
  assesment: "1",
  left_school_date: "",
  bank_address: "",
};
